Add Header and footer
ZPyrolink/ecom-cdlja pull request #1
Opened 2024-11-07 08:48 UTC by m2gi-guidettj

2024-11-07 14:01 UTC, ZPyrolink requested changes
On a un problème de titre de la page : "Translation not found"

2024-11-07 14:01 UTC, ZPyrolink commented on src/main/webapp/app/layouts/navbar/navbar.component.html
> +        <img src="../../../content/images/MenuIcon.png" alt="Menu" />
Il faudrait rajouter une surbrillance lors de l'hover

2024-11-08 08:55 UTC, ZPyrolink requested changes
Le test de la traduction ne marche pas

2024-11-08 09:27 UTC, m2gi-guidettj commented
> Le test de la traduction ne marche pas

j'ai enlevé les tests qui concerne les traductions

2024-11-08 14:45 UTC, ZPyrolink approved these changes

2024-11-08 14:45 UTC, merged