#ws 23 data
ZPyrolink/ecom-cdlja pull request #10
Opened 2024-11-29 13:21 UTC by ndayonga

J'ai testé et l'ajout/suppression d'articles dans le panier marchent bien et mettent à jour le panier.

2024-11-29 14:04 UTC, FlyinthisSky requested changes

2024-11-29 14:04 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +        Set<OrderLine> orderlines = this.getOrderlines();
Faire getOrderlines à la place ne serait pas mieux ?
De plus fait attention, il faut mettre OrderLine et pas Orderline

2024-11-29 14:04 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +            amount += o.getAmountline();
getAmountLine

2024-11-29 14:04 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/service/BasketService.java
> +        SubscribedClients client = optionalClient.orElseThrow();
Regarde dans SubscribedClientsService, il y a une fonction qui getBasket qui permet de recup le panier avec l'adresse mail directement.
Utilise le userService pour récup les donner de l'utilisateur. Ca sent pas très bon quand tu prends directement de Security. Va voir getClientBasket() dans AccountRessource

2024-11-29 14:04 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/service/BasketService.java
> +        order = client.getBasket();
La même que dans ajouter du coup

2024-11-29 14:14 UTC, ndayonga commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +        Set<OrderLine> orderlines = this.getOrderlines();
Ici, je n'ai fait qu'appeler des méthodes déjà existantes. Après, je peux modifier sans souci.

2024-11-29 14:14 UTC, ndayonga commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +            amount += o.getAmountline();
Ici c'est pareil, j'ai appelé une méthode déjà existante

2024-11-29 14:18 UTC, ndayonga commented on src/main/java/fr/cdlja/weebsport/service/BasketService.java
> +        SubscribedClients client = optionalClient.orElseThrow();
Ici, j'ai fait ça parceque le getBasket de Lilou renvoie OrderDTO or je trouvais pratique de récupérer un objet Order directement pour faire les modifications sur les OrderLines et Order sans me casser les pieds avec la conversion de OrderDTO vers Order

2024-11-29 14:38 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +        Set<OrderLine> orderlines = this.getOrderlines();
Ce que je veux dire, c'est qu'en java, faire this.getOrderlines et getOrderlines c'est sensé être la même chose.
Et il faut faire attention, si c'est une fonction créé par un de nous et pas JHipster il faut changer. De même pour le nom des variables qui doit être changé

2024-11-29 14:38 UTC, FlyinthisSky commented on src/main/java/fr/cdlja/weebsport/domain/Order.java
> +            amount += o.getAmountline();
Si c'est pas du JHipster, tu la changes

2024-11-29 15:54 UTC, bouvieli approved these changes

2024-11-29 15:55 UTC, bouvieli approved these changes

2024-11-29 15:57 UTC, m2gi-guidettj approved these changes

2024-11-29 16:00 UTC, m2gi-guidettj approved these changes

2024-11-30 08:13 UTC, bouvieli approved these changes

2024-12-01 20:58 UTC, FlyinthisSky approved these changes

2024-12-01 21:01 UTC, merged