#ws 87 page d un article
ZPyrolink/ecom-cdlja pull request #22
Opened 2024-12-06 17:31 UTC by FlyinthisSky

2024-12-09 10:08 UTC, ZPyrolink commented
Il y a un texte blanc sur blanc. Ca veut aussi dire que le clique s'affiche dans le vide (au survol du texte
![image](https://github.com/user-attachments/assets/164bf2ed-bdf7-4e2e-8bdf-e583151ce59e)
![image](https://github.com/user-attachments/assets/2c8691e6-82ba-459e-b4c8-fe50832f3332)

2024-12-09 10:08 UTC, ZPyrolink commented
Il faudrait aussi tester avec des données qui contiennent plusieurs tailles / couleurs

2024-12-09 10:10 UTC, ZPyrolink requested changes

2024-12-09 10:10 UTC, ZPyrolink commented on src/main/webapp/app/component/product/product.component.html
> +        {{ color.name }}
C'est ici que le texte apparaît en blanc

2024-12-11 08:26 UTC, ZPyrolink requested changes
Un article qui contient plusieurs stocks n'affiche que le premier
Il ne vérifie pas (ou mal) la quantité restante

2024-12-11 13:36 UTC, ZPyrolink approved these changes

2024-12-11 13:37 UTC, m2gi-guidettj approved these changes

2024-12-11 13:37 UTC, merged